# Use NGINX to serve the Angular app
FROM nginx:alpine

# Remove default NGINX html content  
RUN rm -rf /usr/share/nginx/html/*

# Copy the browser folder from current context
COPY browser/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]