name: Send Email
on:
  workflow_call:
    inputs:
      customer_name:
        required: true
        type: string
      application_name:
        required: true
        type: string
      customer_email:
        required: true
        type: string
    secrets:
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true
      VPC_HOST:
        required: true
      VPS_USER:
        required: true
      VPS_PASSWORD:
        required: true
jobs:
  send_invoice_email:
    name: EMAIL to ${{ inputs.customer_name }}
    runs-on: ubuntu-latest
    steps:
     - name: Check file exists on VPS
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.VPC_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          ls -l /home/ApplicationContainer/
          
     - name: Install sshpass
       run: sudo apt-get update && sudo apt-get install -y sshpass
          
     - name: Fetch port using direct SSH
       id: get_port
       run: |
         PORT=$(sshpass -p '${{ secrets.VPS_PASSWORD }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPC_HOST }} "cat /home/ApplicationContainer/${{ inputs.application_name }}_port.txt | tr -d '\r\n' | xargs")
         echo "container_port=$PORT" >> $GITHUB_ENV
         echo "port=$PORT" >> $GITHUB_OUTPUT
         echo "Port extracted: $PORT"

     - name: Set Deployed Application Type
       run: |
         if [[ "${{ inputs.application_name }}" == "leathers_fullapp" ]]; then
          echo "DEPLOYED_APP_TYPE=Leathers Ecommerce application" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "leathers_api" ]]; then
          echo "DEPLOYED_APP_TYPE=Leathers Ecommerce API" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "erp_api" ]]; then
          echo "DEPLOYED_APP_TYPE=ERP API" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "erp_fullapp" ]]; then
          echo "DEPLOYED_APP_TYPE=ERP Application" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "school_fullapp" ]]; then
          echo "DEPLOYED_APP_TYPE=School Application" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "school_api" ]]; then
          echo "DEPLOYED_APP_TYPE=School API" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "college-fullapp" ]]; then
          echo "DEPLOYED_APP_TYPE=College Application" >> $GITHUB_ENV
         elif [[ "${{ inputs.application_name }}" == "college_api" ]]; then
          echo "DEPLOYED_APP_TYPE=College API" >> $GITHUB_ENV
         else
          echo "DEPLOYED_APP_TYPE=Your application" >> $GITHUB_ENV
         fi
     
     - name: Checkout repository
       uses: actions/checkout@v3
        
     - name: Send Purchase Confirmation Email
       uses: dawidd6/action-send-mail@v3
       with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🎉 Purchase Confirmation for Customer: ${{ inputs.customer_name }}"
          to: ${{ inputs.customer_email }}
          from: "Tamu SaaS <${{ secrets.EMAIL_USERNAME }}>"
          body: |
             Dear ${{ inputs.customer_name }},

             🎉 Congratulations! Your ${{ env.DEPLOYED_APP_TYPE }} has been successfully deployed and is now ready for use.

              🔗 You can access your instance using the link below:
              👉 http://${{ secrets.VPC_HOST }}:${{ env.container_port }}

              
               If you have any questions or need assistance, feel free to reach out to our support team.
               Best regards,  
               **Deployment Team**

          attachments: Documentation/${{ inputs.application_name }}.docx
